export const designTokens = {
  color: {
    canvas: "#f7f8fc",
    sidebar: "#f5f7fb",
    surface: "#ffffff",
    surfaceAlt: "#f9fafb",
    primary: "#f00056",
    primaryHover: "#d90452",
    primarySoft: "#ffe7f0",
    secondary: "#4f46e5",
    ink: "#111827",
    textMuted: "#667085",
    textSoft: "#98a2b3",
    border: "#dfe3eb",
    borderStrong: "#c9d1dd",
    success: "#16a34a",
    successSoft: "#dcfce7",
    danger: "#ef4444",
    dangerSoft: "#fee2e2",
    beta: "#4b5563",
    chartBlue: "#4f6bdc",
    chartLime: "#b7dd25",
    chartSlate: "#585d82",
    gradientStart: "#a78bfa",
    gradientMiddle: "#ec4899",
    gradientEnd: "#f00056",
  },
  typography: {
    xs: ["12px", "16px"],
    sm: ["14px", "20px"],
    base: ["16px", "24px"],
    lg: ["20px", "28px"],
    xl: ["30px", "36px"],
  },
  radius: {
    ds: "6px",
    panel: "12px",
    pill: "999px",
  },
  shadow: {
    panel: "0 1px 2px rgba(16, 24, 40, 0.06)",
    focus: "0 0 0 3px rgba(240, 0, 86, 0.12)",
  },
  spacing: {
    4.5: "18px",
  },
} as const;

export const tokenDocumentation = {
  colors: [
    `Primary pink: ${designTokens.color.primary}`,
    `Primary hover: ${designTokens.color.primaryHover}`,
    `Primary soft: ${designTokens.color.primarySoft}`,
    `Canvas: ${designTokens.color.canvas}`,
    `Sidebar: ${designTokens.color.sidebar}`,
    `Surface: ${designTokens.color.surface}`,
    `Border: ${designTokens.color.border}`,
    `Muted text: ${designTokens.color.textMuted}`,
    `Soft text: ${designTokens.color.textSoft}`,
    `Success: ${designTokens.color.success}`,
    `Danger: ${designTokens.color.danger}`,
    `Sola gradient: ${designTokens.color.gradientStart} -> ${designTokens.color.gradientMiddle} -> ${designTokens.color.gradientEnd}`,
  ],
  typography: [
    "30/36 semibold page title",
    "20/28 semibold section title",
    "16/24 semibold metric values",
    "14/20 regular and medium body text",
    "12/16 semibold labels, pills, and meta text",
  ],
  spacing: ["4", "8", "12", "16", "20", "24", "32"],
  radius: ["4px action outlines", "6px inputs and buttons", "8-12px panels", "999px pills"],
  shadows: [designTokens.shadow.panel],
} as const;
